# fly.toml app configuration file generated for financetrackertw on 2026-05-18T12:44:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'financetrackertw'
primary_region = 'nrt'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '15s'
    path = '/'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
