# fly.toml app configuration file generated for financetrackertw on 2026-05-18T14:10:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'financetrackertw'
primary_region = 'nrt'

[build]
  [build.args]
    NEXT_PUBLIC_FIREBASE_API_KEY     = "AIzaSyDONo_JB9b0DEKknfNkXTQOYUhUOTYzIJ0"
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "financetracker-c0cea.firebaseapp.com"
    NEXT_PUBLIC_FIREBASE_PROJECT_ID  = "financetracker-c0cea"
    NEXT_PUBLIC_FIREBASE_APP_ID      = "1:1002903147381:web:bb5fbbe7452f5da0e5393c"

[deploy]
  release_command = 'node_modules/.bin/prisma db push'

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    path = '/login'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
